nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.0.cjs

npmScopes:
  tkww:
    npmAuthToken: "${GITHUB_REGISTRY_NPM_AUTH_TOKEN:-}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"