import Head from "next/head"
import Link from 'next/link'
import { CtaButton } from "@tkww/orion-web-ds-action"
import styles from "@/styles/Home.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>My NextJS App - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.content}>
          <h1>Hello there :)</h1>
          <CtaButton as={Link} treatAs="link" color="primary" href="/mel">Go to Mel&apos;s page</CtaButton>
        </section>
      </main>
    </>
  );
}
