import Head from "next/head"
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { CtaButton } from "@tkww/orion-web-ds-action"
import styles from "@/styles/Page.module.css"

export default function Page() {
  const pathname = usePathname().replace('/', '')

  return (
    <>
      <Head>
        <title>My NextJS App - Mel&apos;s page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.content}>
          <h1>Welcome to {pathname}&apos;s page</h1>
          <CtaButton as={Link} treatAs="link" color="primary-alternative" href="/">Go back to Homepage</CtaButton>
        </section>
      </main>
    </>
  );
}